Задание по основам Rails моделей
naveroot/test_guru_2021 pull request #2
Opened 2021-02-05 08:04 UTC by naveroot

2021-02-05 08:57 UTC, BubuntuClu requested changes

2021-02-05 08:57 UTC, BubuntuClu commented on db/migrate/20210205074113_create_tests.rb
> +
тут по структуре тоже самое что и в SQL задании. внешний ключ надо добавить и индекс на поле внешнего ключа. t.references посмотри эту команду. добавить во всех таблицах надо, где это требуется.
так же надо пушить файл schema.rb

2021-02-06 08:30 UTC, naveroot commented on db/migrate/20210205074113_create_tests.rb
> +
Ага

2021-02-06 14:04 UTC, BubuntuClu requested changes

2021-02-06 14:04 UTC, BubuntuClu commented on db/schema.rb
> +    t.bigint "questions_id"
смотри какой получился нейминг у поля. во множественном числе, это неправильно.

2021-02-06 14:04 UTC, BubuntuClu commented on db/migrate/20210206082034_add_references.rb
> +    add_reference :tests, :categories, foreign_key: true
пока ты делаешь фичу в своей локальной ветке, ты можешь накатывать миграции и откатывать сколько угодно раз, поэтому лучше откатить миграции по созданию таблиц и там внести правки, нежели создавать дополнительный файл, который правит ошибки/упущения/забытые поля.

2021-02-07 18:34 UTC, BubuntuClu commented on db/migrate/20210205074113_create_tests.rb
> +      t.references :category, foreign_key: true
получается так, что ты создаешь табилцу тестов(которая ссылается на таблицу категорий), раньше таблицы категорий

2021-02-22 06:58 UTC, merged